name: request
description: "Suggest an idea for this project"
title: ""
labels: 需要核实
issue_body: true
body:
  - type: markdown
    attributes:
      value: "**Make sure you have read the readme, searched and read the issues related to yours. Otherwise it will be considered as a duplicate which will be closed immediately.**"
  - type: textarea
    id: description
    attributes:
      label: "Describe the feature you want"
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
